sudo: required

services:
  - docker

before_install:
- docker pull sabayon/base-amd64

script:
    - docker run -v $TRAVIS_BUILD_DIR:/entropy sabayon/base-amd64 /entropy/.ci

notifications:
  irc: "chat.freenode.net#sabayon-infra"
